# Generated by Django 3.1.7 on 2021-06-29 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('pid', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('img', models.ImageField(default='/static/default/default.png', upload_to='user/')),
                ('vcf_download', models.IntegerField(default=0)),
                ('qr_generated', models.IntegerField(default=0)),
                ('cover_color', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='social_profile',
            fields=[
                ('pid', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('prof_img', models.ImageField(upload_to='user/')),
                ('cover_img', models.ImageField(blank=True, default='/static/default/cover.jpg', null=True, upload_to='user/')),
                ('name', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('about', models.CharField(blank=True, max_length=500)),
                ('company_logo', models.ImageField(blank=True, default='/static/default/default.png', null=True, upload_to='user/')),
                ('company_name', models.CharField(blank=True, max_length=500)),
                ('about_company', models.CharField(blank=True, max_length=500)),
                ('email', models.EmailField(max_length=500)),
                ('contact', models.CharField(max_length=500)),
                ('facebook_social_links', models.URLField(blank=True, max_length=500, null=True)),
                ('twitter_social_links', models.URLField(blank=True, max_length=500, null=True)),
                ('instagram_social_links', models.URLField(blank=True, max_length=500, null=True)),
                ('linkedin_social_links', models.URLField(blank=True, max_length=500, null=True)),
                ('website_social_links', models.URLField(blank=True, max_length=500, null=True)),
                ('longitude', models.FloatField(blank=True, max_length=500, null=True)),
                ('latitude', models.FloatField(blank=True, max_length=500, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='user/')),
                ('qr_type', models.CharField(blank=True, max_length=1, null=True)),
                ('qr_color', models.CharField(blank=True, max_length=50, null=True)),
                ('qr_logo', models.ImageField(blank=True, null=True, upload_to='user/')),
            ],
        ),
        migrations.CreateModel(
            name='upload_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='save/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cname', models.CharField(blank=True, max_length=100)),
                ('des', models.CharField(blank=True, max_length=500)),
                ('email', models.EmailField(blank=True, max_length=30)),
                ('contact', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('pid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user/')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
