# Generated by Django 3.1.7 on 2021-06-30 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210629_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='social_profile',
            name='current_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 30, 20, 17, 53, 117768)),
        ),
    ]
