# Generated by Django 3.1.7 on 2021-07-02 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_social_profile_current_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qr_style',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='share_style',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='vcf_style',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='social_profile',
            name='current_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 23, 43, 5, 757693)),
        ),
    ]
