# Generated by Django 3.2.4 on 2021-07-16 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210702_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='qr_style',
            field=models.CharField(blank=True, default='color:black', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='social_profile',
            name='current_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 16, 11, 6, 54, 983426)),
        ),
    ]
